import 'tui-pagination/dist/tui-pagination.css';
import '../sass/main.scss';
import './verify-localstorage';
import './tui_pagination';
import './request-popular-movies';
import './request-id-movie';
import './request-genres';
import './gradient-granim.js';
import './disableEnter.js'
import './request-input-movies';
import './switch-home-liberary';
import './team-modal';
import './switch-language';
